(PROGN (SYSFLAG 1 NIL) (QUOTE READY))
(DE TST NIL
  (PROG (I R)
        (SETQ I 0)
        (SETQ R 0)
   LP   (SET (QUOTE GV) (CONS 1 2))
        (RPLACD GV 7)
        (PUTPROP (QUOTE GV) (QUOTE P) 1)
        (COND ((ATOM GV) (SETQ R (ADD1 R))))
        (COND ((NLISTP GV) (SETQ R (ADD1 R))))
        (COND ((NULL (LISTP GV)) (SETQ R (ADD1 R))))
        (SETQ I (ADD1 I))
        (COND ((LESSP I 40000) (GO LP)))
        (RETURN R)))
(TST)
(EXIT)
