(SETQ G (FUNCTION (LAMBDA (X) X) NIL))
G
(APPLY G (QUOTE (3)))
(APPLY (FUNCTION (LAMBDA (X) X)) (QUOTE (3)))
(DE MK2 (V) (FUNCTION (LAMBDA (X) X) V))
(APPLY (MK2 NIL) (QUOTE (3)))
(APPLY (MK2 (QUOTE (A))) (QUOTE (3)))
(EXIT)
