(SYSFLAG 1 NIL)
(SUBSTRING "abcdef" 1 0)
(SUBSTRING "abcdef" 2 0)
(SUBSTRING "abcdef" 0 6)
(SUBSTRING "abcdef" 0 0)
(SUBSTRING "abcdef" -6 -3)
(SUBSTRING "abcdef" -3 NIL)
(SUBSTRING "abcdef" 2 6)
(SUBSTRING "abcdef" 7 NIL)
(SUBSTRING "abcdef" -8 NIL)
(EXIT)
