COMMON AND INTEGER DECLARATIONS
      COMMON /A/
     * NAREA ,JBYTES,IBYTES,BYTES ,CHDIV ,MAXINT,MAXBIG,MAXREC,NATOMP,
     * NFREEP,JBP   ,NUMBP ,NFREET,NUMADD,NPNAME,NFREEB,NATOM ,NSTACK,
     * NHTAB ,BIGNUM,ISMALL,DPNP  ,DPNAME,IPROMP,NATHSH,NBYTES,NCHTYP,
     * NBMESS,MAXMES,IRESOL,IPOWER,BIGMAX,FUZZ,
     * GARBS ,CGARBS,NGARBS,AGARBS,RMAX
      COMMON /B/
     * ARG   ,ARG2  ,ARG3  ,ALIST ,FORM  ,
     * TEMP1 ,TEMP2 ,TEMP3 ,I1CONS,I2CONS,NARGS ,
     * NIL   ,A000  ,APPLY ,EVAL  ,FNCELL,FEXPR ,FUNARG,LAMBDA,ARRAY ,
     * STRING,SUBSTR,LISPX ,NLAMBD,UNBOUN,PROG  ,QUOTE ,EXPR  ,ERROR ,
     * SFORM ,SINTER ,SUBARG,DOTAT ,T     ,
     * SUBR0 ,SUBR11,SUBR1 ,SUBR2 ,SUBR3 ,SUBR  ,FSUBR ,
     * IP    ,JP    ,IPP   ,JPP   ,MIDDL ,ABUP1 ,CHT   ,CHR   ,NUMGEN,
     * UNUSED,BRLEV ,BRFLG ,IFLG1 ,IFLG2 ,ISPLFT,IBREAK,ERRTYP,
     * IOBUFF,MAXLUN,LUNSYS,LUNINS,LUNUTS,MAXPAR,ITABWG,
     * LUNIN ,RDPOS ,LMARGR,MARGR ,LUNUT ,PRTPOS,LMARG ,MARG  ,LEVELL,
     * LEVELP,
     * DREG(7),ABUFF(160),RDBUFF(160),PRBUFF(160),BUFF(160),
     * IMESS(400),PNAME(5000),PNP(3000),
     * HTAB(4000),STACK(1500)
      COMMON /CARCDR/
     * CAR(100000),CDR(100000),CHTAB(256)
      COMMON /CHARS/
     * SPACE ,LPAR  ,RPAR  ,ILBCHR,IRBCHR,STRCHR,IQCHR ,UBR   ,DOT   ,
     * ITCHR ,IPLUS ,IMINUS,IFIG(10),ATEND ,SOFTBR,ECHAR ,NOCHAR
      COMMON /JAAN/
     * JILL(1500),JACK(1500),ENV,TOPS,HILL,HILLW
      LOGICAL IBREAK
      REAL BIGMAX,FUZZ,PNAME,RMAX
      INTEGER 
     * ENV,TOPS,IPROMP,HILL,HILLW,JILL,JACK,SINTER,SFORM,SUBARG,
     * BYTES ,CHDIV ,BIGNUM,DPNP  ,DPNAME,GARBS ,CGARBS,AGARBS,
     * ARG   ,ARG2  ,ARG3  ,ALIST ,FORM  ,TEMP1 ,TEMP2 ,TEMP3 ,
     * A000  ,APPLY ,EVAL  ,FNCELL,FEXPR ,FUNARG,ARRAY ,STRING,SUBSTR,
     * UNBOUN,PROG  ,QUOTE ,EXPR  ,ERROR ,DOTAT ,T     ,
     * SUBR0 ,SUBR11,SUBR1 ,SUBR2 ,SUBR3 ,SUBR  ,FSUBR ,
     * ABUP1 ,CHT   ,CHR   ,UNUSED,BRLEV ,BRFLG ,ERRTYP,
     * RDPOS ,PRTPOS,DREG  ,ABUFF ,RDBUFF,PRBUFF,BUFF  ,
     * SPACE ,RPAR  ,STRCHR,UBR   ,DOT   ,ATEND ,SOFTBR,ECHAR
      INTEGER*4 HTAB  ,STACK ,CAR   ,CDR   ,CHTAB ,PNP
     
COMMON AND INTEGER DECLARATIONS END



