# Makefile for Windows

#F2C = \f2c-new\f2c
#LIB = \f2c-new\vcf2c.lib
#INCDIR = \f2c-new


LAST_UPDATE_YEAR = 2026
LAST_UPDATE_MONTH = 8
LAST_UPDATE_DAY = 4

# Set defaults
PARMS = -DCELLS=100000 -DATOMS=3000 -DSTACK=1500 -DARRAY=5000


#CFLAGS = -nologo -Zi -Od $(PARMS) -DYEAR=$(LAST_UPDATE_YEAR) -DMONTH=$(LAST_UPDATE_MONTH) -DDAY=$(LAST_UPDATE_DAY)
CFLAGS = -nologo -O2 $(PARMS) -DYEAR=$(LAST_UPDATE_YEAR) -DMONTH=$(LAST_UPDATE_MONTH) -DDAY=$(LAST_UPDATE_DAY)
FFLAGS =  -onetrip -A -h

# NEVER regenerate the C from the FORTRAN -- see the note in Makefile and in
# CLAUDE.md.  The rule that used to stand here referred to an undefined $(F2C),
# and NMAKE finds "lispf41.f" as Lispf41.f on a case-insensitive filesystem.

# basic.img is built by loading these into bare.img -- see script.2.
LISPSRC = basic1.lisp basic2.lisp io1.lisp func1.lisp debug1.lisp \
          debug2.lisp edit.lisp makef.lisp history.lisp

basic.img : bare.img script.2 $(LISPSRC)
	lispf4 bare.img <script.2

bare.img : lispf4.exe SYSATOMS script.1
	lispf4 -x <script.1


lispf4.exe : lispf41.obj lispf42.obj auxillary.obj
	cl $(CFLAGS) -Felispf4.exe lispf41.obj lispf42.obj auxillary.obj

lispf41.obj lispf42.obj auxillary.obj : f2c.h lispf4.h

#lispf41.c : lispf41.f
#	$(F2C) $(FFLAGS) $<

#lispf42.c : lispf42.f
#	$(F2C) $(FFLAGS) -E $<

#lispf41.obj : lispf41.c

#lispf41.obj : lispf41.c

clean:
	del /q /f *.o *.obj *.bak *.pdb *.ilk *.opt 2>nul

realclean: clean
	del /q /f lispf4.exe *.img 2>nul
